export const countrys = [
  {
    name: "Afghanistan",
    capital: "Kabul",
    region: "Asia",
    population: 27657145,
  },
  {
    name: "Åland Islands",
    capital: "Mariehamn",
    region: "Europe",
    population: 28875,
  },
  {
    name: "Albania",
    capital: "Tirana",
    region: "Europe",
    population: 2886026,
  },
  {
    name: "Algeria",
    capital: "Algiers",
    region: "Africa",
    population: 40400000,
  },
  {
    name: "American Samoa",
    capital: "Pago Pago",
    region: "Oceania",
    population: 57100,
  },
  {
    name: "Andorra",
    capital: "Andorra la Vella",
    region: "Europe",
    population: 78014,
  },
  {
    name: "Angola",
    capital: "Luanda",
    region: "Africa",
    population: 25868000,
  },
  {
    name: "Anguilla",
    capital: "The Valley",
    region: "Americas",
    population: 13452,
  },
  {
    name: "Antarctica",
    capital: "",
    region: "Polar",
    population: 1000,
  },
  {
    name: "Antigua and Barbuda",
    capital: "Saint John's",
    region: "Americas",
    population: 86295,
  },
  {
    name: "Argentina",
    capital: "Buenos Aires",
    region: "Americas",
    population: 43590400,
  },
  {
    name: "Armenia",
    capital: "Yerevan",
    region: "Asia",
    population: 2994400,
  },
  {
    name: "Aruba",
    capital: "Oranjestad",
    region: "Americas",
    population: 107394,
  },
  {
    name: "Australia",
    capital: "Canberra",
    region: "Oceania",
    population: 24117360,
  },
  {
    name: "Austria",
    capital: "Vienna",
    region: "Europe",
    population: 8725931,
  },
  {
    name: "Azerbaijan",
    capital: "Baku",
    region: "Asia",
    population: 9730500,
  },
  {
    name: "Bahamas",
    capital: "Nassau",
    region: "Americas",
    population: 378040,
  },
  {
    name: "Bahrain",
    capital: "Manama",
    region: "Asia",
    population: 1404900,
  },
  {
    name: "Bangladesh",
    capital: "Dhaka",
    region: "Asia",
    population: 161006790,
  },
  {
    name: "Barbados",
    capital: "Bridgetown",
    region: "Americas",
    population: 285000,
  },
  {
    name: "Belarus",
    capital: "Minsk",
    region: "Europe",
    population: 9498700,
  },
  {
    name: "Belgium",
    capital: "Brussels",
    region: "Europe",
    population: 11319511,
  },
  {
    name: "Belize",
    capital: "Belmopan",
    region: "Americas",
    population: 370300,
  },
  {
    name: "Benin",
    capital: "Porto-Novo",
    region: "Africa",
    population: 10653654,
  },
  {
    name: "Bermuda",
    capital: "Hamilton",
    region: "Americas",
    population: 61954,
  },
  {
    name: "Bhutan",
    capital: "Thimphu",
    region: "Asia",
    population: 775620,
  },
  {
    name: "Bolivia (Plurinational State of)",
    capital: "Sucre",
    region: "Americas",
    population: 10985059,
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    capital: "Kralendijk",
    region: "Americas",
    population: 17408,
  },
  {
    name: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    region: "Europe",
    population: 3531159,
  },
  {
    name: "Botswana",
    capital: "Gaborone",
    region: "Africa",
    population: 2141206,
  },
  {
    name: "Bouvet Island",
    capital: "",
    region: "",
    population: 0,
  },
  {
    name: "Brazil",
    capital: "Brasília",
    region: "Americas",
    population: 206135893,
  },
  {
    name: "British Indian Ocean Territory",
    capital: "Diego Garcia",
    region: "Africa",
    population: 3000,
  },
  {
    name: "United States Minor Outlying Islands",
    capital: "",
    region: "Americas",
    population: 300,
  },
  {
    name: "Virgin Islands (British)",
    capital: "Road Town",
    region: "Americas",
    population: 28514,
  },
  {
    name: "Virgin Islands (U.S.)",
    capital: "Charlotte Amalie",
    region: "Americas",
    population: 114743,
  },
  {
    name: "Brunei Darussalam",
    capital: "Bandar Seri Begawan",
    region: "Asia",
    population: 411900,
  },
  {
    name: "Bulgaria",
    capital: "Sofia",
    region: "Europe",
    population: 7153784,
  },
  {
    name: "Burkina Faso",
    capital: "Ouagadougou",
    region: "Africa",
    population: 19034397,
  },
  {
    name: "Burundi",
    capital: "Bujumbura",
    region: "Africa",
    population: 10114505,
  },
  {
    name: "Cambodia",
    capital: "Phnom Penh",
    region: "Asia",
    population: 15626444,
  },
  {
    name: "Cameroon",
    capital: "Yaoundé",
    region: "Africa",
    population: 22709892,
  },
  {
    name: "Canada",
    capital: "Ottawa",
    region: "Americas",
    population: 36155487,
  },
  {
    name: "Cabo Verde",
    capital: "Praia",
    region: "Africa",
    population: 531239,
  },
  {
    name: "Cayman Islands",
    capital: "George Town",
    region: "Americas",
    population: 58238,
  },
  {
    name: "Central African Republic",
    capital: "Bangui",
    region: "Africa",
    population: 4998000,
  },
  {
    name: "Chad",
    capital: "N'Djamena",
    region: "Africa",
    population: 14497000,
  },
  {
    name: "Chile",
    capital: "Santiago",
    region: "Americas",
    population: 18191900,
  },
  {
    name: "China",
    capital: "Beijing",
    region: "Asia",
    population: 1377422166,
  },
  {
    name: "Christmas Island",
    capital: "Flying Fish Cove",
    region: "Oceania",
    population: 2072,
  },
  {
    name: "Cocos (Keeling) Islands",
    capital: "West Island",
    region: "Oceania",
    population: 550,
  },
  {
    name: "Colombia",
    capital: "Bogotá",
    region: "Americas",
    population: 48759958,
  },
  {
    name: "Comoros",
    capital: "Moroni",
    region: "Africa",
    population: 806153,
  },
  {
    name: "Congo",
    capital: "Brazzaville",
    region: "Africa",
    population: 4741000,
  },
  {
    name: "Congo (Democratic Republic of the)",
    capital: "Kinshasa",
    region: "Africa",
    population: 85026000,
  },
  {
    name: "Cook Islands",
    capital: "Avarua",
    region: "Oceania",
    population: 18100,
  },
  {
    name: "Costa Rica",
    capital: "San José",
    region: "Americas",
    population: 4890379,
  },
  {
    name: "Croatia",
    capital: "Zagreb",
    region: "Europe",
    population: 4190669,
  },
  {
    name: "Cuba",
    capital: "Havana",
    region: "Americas",
    population: 11239004,
  },
  {
    name: "Curaçao",
    capital: "Willemstad",
    region: "Americas",
    population: 154843,
  },
  {
    name: "Cyprus",
    capital: "Nicosia",
    region: "Europe",
    population: 847000,
  },
  {
    name: "Czech Republic",
    capital: "Prague",
    region: "Europe",
    population: 10558524,
  },
  {
    name: "Denmark",
    capital: "Copenhagen",
    region: "Europe",
    population: 5717014,
  },
  {
    name: "Djibouti",
    capital: "Djibouti",
    region: "Africa",
    population: 900000,
  },
  {
    name: "Dominica",
    capital: "Roseau",
    region: "Americas",
    population: 71293,
  },
  {
    name: "Dominican Republic",
    capital: "Santo Domingo",
    region: "Americas",
    population: 10075045,
  },
  {
    name: "Ecuador",
    capital: "Quito",
    region: "Americas",
    population: 16545799,
  },
  {
    name: "Egypt",
    capital: "Cairo",
    region: "Africa",
    population: 91290000,
  },
  {
    name: "El Salvador",
    capital: "San Salvador",
    region: "Americas",
    population: 6520675,
  },
  {
    name: "Equatorial Guinea",
    capital: "Malabo",
    region: "Africa",
    population: 1222442,
  },
  {
    name: "Eritrea",
    capital: "Asmara",
    region: "Africa",
    population: 5352000,
  },
  {
    name: "Estonia",
    capital: "Tallinn",
    region: "Europe",
    population: 1315944,
  },
  {
    name: "Ethiopia",
    capital: "Addis Ababa",
    region: "Africa",
    population: 92206005,
  },
  {
    name: "Falkland Islands (Malvinas)",
    capital: "Stanley",
    region: "Americas",
    population: 2563,
  },
  {
    name: "Faroe Islands",
    capital: "Tórshavn",
    region: "Europe",
    population: 49376,
  },
  {
    name: "Fiji",
    capital: "Suva",
    region: "Oceania",
    population: 867000,
  },
  {
    name: "Finland",
    capital: "Helsinki",
    region: "Europe",
    population: 5491817,
  },
  {
    name: "France",
    capital: "Paris",
    region: "Europe",
    population: 66710000,
  },
  {
    name: "French Guiana",
    capital: "Cayenne",
    region: "Americas",
    population: 254541,
  },
  {
    name: "French Polynesia",
    capital: "Papeetē",
    region: "Oceania",
    population: 271800,
  },
  {
    name: "French Southern Territories",
    capital: "Port-aux-Français",
    region: "Africa",
    population: 140,
  },
  {
    name: "Gabon",
    capital: "Libreville",
    region: "Africa",
    population: 1802278,
  },
  {
    name: "Gambia",
    capital: "Banjul",
    region: "Africa",
    population: 1882450,
  },
  {
    name: "Georgia",
    capital: "Tbilisi",
    region: "Asia",
    population: 3720400,
  },
  {
    name: "Germany",
    capital: "Berlin",
    region: "Europe",
    population: 81770900,
  },
  {
    name: "Ghana",
    capital: "Accra",
    region: "Africa",
    population: 27670174,
  },
  {
    name: "Gibraltar",
    capital: "Gibraltar",
    region: "Europe",
    population: 33140,
  },
  {
    name: "Greece",
    capital: "Athens",
    region: "Europe",
    population: 10858018,
  },
  {
    name: "Greenland",
    capital: "Nuuk",
    region: "Americas",
    population: 55847,
  },
  {
    name: "Grenada",
    capital: "St. George's",
    region: "Americas",
    population: 103328,
  },
  {
    name: "Guadeloupe",
    capital: "Basse-Terre",
    region: "Americas",
    population: 400132,
  },
  {
    name: "Guam",
    capital: "Hagåtña",
    region: "Oceania",
    population: 184200,
  },
  {
    name: "Guatemala",
    capital: "Guatemala City",
    region: "Americas",
    population: 16176133,
  },
  {
    name: "Guernsey",
    capital: "St. Peter Port",
    region: "Europe",
    population: 62999,
  },
  {
    name: "Guinea",
    capital: "Conakry",
    region: "Africa",
    population: 12947000,
  },
  {
    name: "Guinea-Bissau",
    capital: "Bissau",
    region: "Africa",
    population: 1547777,
  },
  {
    name: "Guyana",
    capital: "Georgetown",
    region: "Americas",
    population: 746900,
  },
  {
    name: "Haiti",
    capital: "Port-au-Prince",
    region: "Americas",
    population: 11078033,
  },
  {
    name: "Heard Island and McDonald Islands",
    capital: "",
    region: "",
    population: 0,
  },
  {
    name: "Holy See",
    capital: "Rome",
    region: "Europe",
    population: 451,
  },
  {
    name: "Honduras",
    capital: "Tegucigalpa",
    region: "Americas",
    population: 8576532,
  },
  {
    name: "Hong Kong",
    capital: "City of Victoria",
    region: "Asia",
    population: 7324300,
  },
  {
    name: "Hungary",
    capital: "Budapest",
    region: "Europe",
    population: 9823000,
  },
  {
    name: "Iceland",
    capital: "Reykjavík",
    region: "Europe",
    population: 334300,
  },
  {
    name: "India",
    capital: "New Delhi",
    region: "Asia",
    population: 1295210000,
  },
  {
    name: "Indonesia",
    capital: "Jakarta",
    region: "Asia",
    population: 258705000,
  },
  {
    name: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    region: "Africa",
    population: 22671331,
  },
  {
    name: "Iran (Islamic Republic of)",
    capital: "Tehran",
    region: "Asia",
    population: 79369900,
  },
  {
    name: "Iraq",
    capital: "Baghdad",
    region: "Asia",
    population: 37883543,
  },
  {
    name: "Ireland",
    capital: "Dublin",
    region: "Europe",
    population: 6378000,
  },
  {
    name: "Isle of Man",
    capital: "Douglas",
    region: "Europe",
    population: 84497,
  },
  {
    name: "Israel",
    capital: "Jerusalem",
    region: "Asia",
    population: 8527400,
  },
  {
    name: "Italy",
    capital: "Rome",
    region: "Europe",
    population: 60665551,
  },
  {
    name: "Jamaica",
    capital: "Kingston",
    region: "Americas",
    population: 2723246,
  },
  {
    name: "Japan",
    capital: "Tokyo",
    region: "Asia",
    population: 126960000,
  },
  {
    name: "Jersey",
    capital: "Saint Helier",
    region: "Europe",
    population: 100800,
  },
  {
    name: "Jordan",
    capital: "Amman",
    region: "Asia",
    population: 9531712,
  },
  {
    name: "Kazakhstan",
    capital: "Astana",
    region: "Asia",
    population: 17753200,
  },
  {
    name: "Kenya",
    capital: "Nairobi",
    region: "Africa",
    population: 47251000,
  },
  {
    name: "Kiribati",
    capital: "South Tarawa",
    region: "Oceania",
    population: 113400,
  },
  {
    name: "Kuwait",
    capital: "Kuwait City",
    region: "Asia",
    population: 4183658,
  },
  {
    name: "Kyrgyzstan",
    capital: "Bishkek",
    region: "Asia",
    population: 6047800,
  },
  {
    name: "Lao People's Democratic Republic",
    capital: "Vientiane",
    region: "Asia",
    population: 6492400,
  },
  {
    name: "Latvia",
    capital: "Riga",
    region: "Europe",
    population: 1961600,
  },
  {
    name: "Lebanon",
    capital: "Beirut",
    region: "Asia",
    population: 5988000,
  },
  {
    name: "Lesotho",
    capital: "Maseru",
    region: "Africa",
    population: 1894194,
  },
  {
    name: "Liberia",
    capital: "Monrovia",
    region: "Africa",
    population: 4615000,
  },
  {
    name: "Libya",
    capital: "Tripoli",
    region: "Africa",
    population: 6385000,
  },
  {
    name: "Liechtenstein",
    capital: "Vaduz",
    region: "Europe",
    population: 37623,
  },
  {
    name: "Lithuania",
    capital: "Vilnius",
    region: "Europe",
    population: 2872294,
  },
  {
    name: "Luxembourg",
    capital: "Luxembourg",
    region: "Europe",
    population: 576200,
  },
  {
    name: "Macao",
    capital: "",
    region: "Asia",
    population: 649100,
  },
  {
    name: "Macedonia (the former Yugoslav Republic of)",
    capital: "Skopje",
    region: "Europe",
    population: 2058539,
  },
  {
    name: "Madagascar",
    capital: "Antananarivo",
    region: "Africa",
    population: 22434363,
  },
  {
    name: "Malawi",
    capital: "Lilongwe",
    region: "Africa",
    population: 16832910,
  },
  {
    name: "Malaysia",
    capital: "Kuala Lumpur",
    region: "Asia",
    population: 31405416,
  },
  {
    name: "Maldives",
    capital: "Malé",
    region: "Asia",
    population: 344023,
  },
  {
    name: "Mali",
    capital: "Bamako",
    region: "Africa",
    population: 18135000,
  },
  {
    name: "Malta",
    capital: "Valletta",
    region: "Europe",
    population: 425384,
  },
  {
    name: "Marshall Islands",
    capital: "Majuro",
    region: "Oceania",
    population: 54880,
  },
  {
    name: "Martinique",
    capital: "Fort-de-France",
    region: "Americas",
    population: 378243,
  },
  {
    name: "Mauritania",
    capital: "Nouakchott",
    region: "Africa",
    population: 3718678,
  },
  {
    name: "Mauritius",
    capital: "Port Louis",
    region: "Africa",
    population: 1262879,
  },
  {
    name: "Mayotte",
    capital: "Mamoudzou",
    region: "Africa",
    population: 226915,
  },
  {
    name: "Mexico",
    capital: "Mexico City",
    region: "Americas",
    population: 122273473,
  },
  {
    name: "Micronesia (Federated States of)",
    capital: "Palikir",
    region: "Oceania",
    population: 102800,
  },
  {
    name: "Moldova (Republic of)",
    capital: "Chișinău",
    region: "Europe",
    population: 3553100,
  },
  {
    name: "Monaco",
    capital: "Monaco",
    region: "Europe",
    population: 38400,
  },
  {
    name: "Mongolia",
    capital: "Ulan Bator",
    region: "Asia",
    population: 3093100,
  },
  {
    name: "Montenegro",
    capital: "Podgorica",
    region: "Europe",
    population: 621810,
  },
  {
    name: "Montserrat",
    capital: "Plymouth",
    region: "Americas",
    population: 4922,
  },
  {
    name: "Morocco",
    capital: "Rabat",
    region: "Africa",
    population: 33337529,
  },
  {
    name: "Mozambique",
    capital: "Maputo",
    region: "Africa",
    population: 26423700,
  },
  {
    name: "Myanmar",
    capital: "Naypyidaw",
    region: "Asia",
    population: 51419420,
  },
  {
    name: "Namibia",
    capital: "Windhoek",
    region: "Africa",
    population: 2324388,
  },
  {
    name: "Nauru",
    capital: "Yaren",
    region: "Oceania",
    population: 10084,
  },
  {
    name: "Nepal",
    capital: "Kathmandu",
    region: "Asia",
    population: 28431500,
  },
  {
    name: "Netherlands",
    capital: "Amsterdam",
    region: "Europe",
    population: 17019800,
  },
  {
    name: "New Caledonia",
    capital: "Nouméa",
    region: "Oceania",
    population: 268767,
  },
  {
    name: "New Zealand",
    capital: "Wellington",
    region: "Oceania",
    population: 4697854,
  },
  {
    name: "Nicaragua",
    capital: "Managua",
    region: "Americas",
    population: 6262703,
  },
  {
    name: "Niger",
    capital: "Niamey",
    region: "Africa",
    population: 20715000,
  },
  {
    name: "Nigeria",
    capital: "Abuja",
    region: "Africa",
    population: 186988000,
  },
  {
    name: "Niue",
    capital: "Alofi",
    region: "Oceania",
    population: 1470,
  },
  {
    name: "Norfolk Island",
    capital: "Kingston",
    region: "Oceania",
    population: 2302,
  },
  {
    name: "Korea (Democratic People's Republic of)",
    capital: "Pyongyang",
    region: "Asia",
    population: 25281000,
  },
  {
    name: "Northern Mariana Islands",
    capital: "Saipan",
    region: "Oceania",
    population: 56940,
  },
  {
    name: "Norway",
    capital: "Oslo",
    region: "Europe",
    population: 5223256,
  },
  {
    name: "Oman",
    capital: "Muscat",
    region: "Asia",
    population: 4420133,
  },
  {
    name: "Pakistan",
    capital: "Islamabad",
    region: "Asia",
    population: 194125062,
  },
  {
    name: "Palau",
    capital: "Ngerulmud",
    region: "Oceania",
    population: 17950,
  },
  {
    name: "Palestine, State of",
    capital: "Ramallah",
    region: "Asia",
    population: 4682467,
  },
  {
    name: "Panama",
    capital: "Panama City",
    region: "Americas",
    population: 3814672,
  },
  {
    name: "Papua New Guinea",
    capital: "Port Moresby",
    region: "Oceania",
    population: 8083700,
  },
  {
    name: "Paraguay",
    capital: "Asunción",
    region: "Americas",
    population: 6854536,
  },
  {
    name: "Peru",
    capital: "Lima",
    region: "Americas",
    population: 31488700,
  },
  {
    name: "Philippines",
    capital: "Manila",
    region: "Asia",
    population: 103279800,
  },
  {
    name: "Pitcairn",
    capital: "Adamstown",
    region: "Oceania",
    population: 56,
  },
  {
    name: "Poland",
    capital: "Warsaw",
    region: "Europe",
    population: 38437239,
  },
  {
    name: "Portugal",
    capital: "Lisbon",
    region: "Europe",
    population: 10374822,
  },
  {
    name: "Puerto Rico",
    capital: "San Juan",
    region: "Americas",
    population: 3474182,
  },
  {
    name: "Qatar",
    capital: "Doha",
    region: "Asia",
    population: 2587564,
  },
  {
    name: "Republic of Kosovo",
    capital: "Pristina",
    region: "Europe",
    population: 1733842,
  },
  {
    name: "Réunion",
    capital: "Saint-Denis",
    region: "Africa",
    population: 840974,
  },
  {
    name: "Romania",
    capital: "Bucharest",
    region: "Europe",
    population: 19861408,
  },
  {
    name: "Russian Federation",
    capital: "Moscow",
    region: "Europe",
    population: 146599183,
  },
  {
    name: "Rwanda",
    capital: "Kigali",
    region: "Africa",
    population: 11553188,
  },
  {
    name: "Saint Barthélemy",
    capital: "Gustavia",
    region: "Americas",
    population: 9417,
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    capital: "Jamestown",
    region: "Africa",
    population: 4255,
  },
  {
    name: "Saint Kitts and Nevis",
    capital: "Basseterre",
    region: "Americas",
    population: 46204,
  },
  {
    name: "Saint Lucia",
    capital: "Castries",
    region: "Americas",
    population: 186000,
  },
  {
    name: "Saint Martin (French part)",
    capital: "Marigot",
    region: "Americas",
    population: 36979,
  },
  {
    name: "Saint Pierre and Miquelon",
    capital: "Saint-Pierre",
    region: "Americas",
    population: 6069,
  },
  {
    name: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    region: "Americas",
    population: 109991,
  },
  {
    name: "Samoa",
    capital: "Apia",
    region: "Oceania",
    population: 194899,
  },
  {
    name: "San Marino",
    capital: "City of San Marino",
    region: "Europe",
    population: 33005,
  },
  {
    name: "Sao Tome and Principe",
    capital: "São Tomé",
    region: "Africa",
    population: 187356,
  },
  {
    name: "Saudi Arabia",
    capital: "Riyadh",
    region: "Asia",
    population: 32248200,
  },
  {
    name: "Senegal",
    capital: "Dakar",
    region: "Africa",
    population: 14799859,
  },
  {
    name: "Serbia",
    capital: "Belgrade",
    region: "Europe",
    population: 7076372,
  },
  {
    name: "Seychelles",
    capital: "Victoria",
    region: "Africa",
    population: 91400,
  },
  {
    name: "Sierra Leone",
    capital: "Freetown",
    region: "Africa",
    population: 7075641,
  },
  {
    name: "Singapore",
    capital: "Singapore",
    region: "Asia",
    population: 5535000,
  },
  {
    name: "Sint Maarten (Dutch part)",
    capital: "Philipsburg",
    region: "Americas",
    population: 38247,
  },
  {
    name: "Slovakia",
    capital: "Bratislava",
    region: "Europe",
    population: 5426252,
  },
  {
    name: "Slovenia",
    capital: "Ljubljana",
    region: "Europe",
    population: 2064188,
  },
  {
    name: "Solomon Islands",
    capital: "Honiara",
    region: "Oceania",
    population: 642000,
  },
  {
    name: "Somalia",
    capital: "Mogadishu",
    region: "Africa",
    population: 11079000,
  },
  {
    name: "South Africa",
    capital: "Pretoria",
    region: "Africa",
    population: 55653654,
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    capital: "King Edward Point",
    region: "Americas",
    population: 30,
  },
  {
    name: "Korea (Republic of)",
    capital: "Seoul",
    region: "Asia",
    population: 50801405,
  },
  {
    name: "South Sudan",
    capital: "Juba",
    region: "Africa",
    population: 12131000,
  },
  {
    name: "Spain",
    capital: "Madrid",
    region: "Europe",
    population: 46438422,
  },
  {
    name: "Sri Lanka",
    capital: "Colombo",
    region: "Asia",
    population: 20966000,
  },
  {
    name: "Sudan",
    capital: "Khartoum",
    region: "Africa",
    population: 39598700,
  },
  {
    name: "Suriname",
    capital: "Paramaribo",
    region: "Americas",
    population: 541638,
  },
  {
    name: "Svalbard and Jan Mayen",
    capital: "Longyearbyen",
    region: "Europe",
    population: 2562,
  },
  {
    name: "Swaziland",
    capital: "Lobamba",
    region: "Africa",
    population: 1132657,
  },
  {
    name: "Sweden",
    capital: "Stockholm",
    region: "Europe",
    population: 9894888,
  },
  {
    name: "Switzerland",
    capital: "Bern",
    region: "Europe",
    population: 8341600,
  },
  {
    name: "Syrian Arab Republic",
    capital: "Damascus",
    region: "Asia",
    population: 18564000,
  },
  {
    name: "Taiwan",
    capital: "Taipei",
    region: "Asia",
    population: 23503349,
  },
  {
    name: "Tajikistan",
    capital: "Dushanbe",
    region: "Asia",
    population: 8593600,
  },
  {
    name: "Tanzania, United Republic of",
    capital: "Dodoma",
    region: "Africa",
    population: 55155000,
  },
  {
    name: "Thailand",
    capital: "Bangkok",
    region: "Asia",
    population: 65327652,
  },
  {
    name: "Timor-Leste",
    capital: "Dili",
    region: "Asia",
    population: 1167242,
  },
  {
    name: "Togo",
    capital: "Lomé",
    region: "Africa",
    population: 7143000,
  },
  {
    name: "Tokelau",
    capital: "Fakaofo",
    region: "Oceania",
    population: 1411,
  },
  {
    name: "Tonga",
    capital: "Nuku'alofa",
    region: "Oceania",
    population: 103252,
  },
  {
    name: "Trinidad and Tobago",
    capital: "Port of Spain",
    region: "Americas",
    population: 1349667,
  },
  {
    name: "Tunisia",
    capital: "Tunis",
    region: "Africa",
    population: 11154400,
  },
  {
    name: "Turkey",
    capital: "Ankara",
    region: "Asia",
    population: 78741053,
  },
  {
    name: "Turkmenistan",
    capital: "Ashgabat",
    region: "Asia",
    population: 4751120,
  },
  {
    name: "Turks and Caicos Islands",
    capital: "Cockburn Town",
    region: "Americas",
    population: 31458,
  },
  {
    name: "Tuvalu",
    capital: "Funafuti",
    region: "Oceania",
    population: 10640,
  },
  {
    name: "Uganda",
    capital: "Kampala",
    region: "Africa",
    population: 33860700,
  },
  {
    name: "Ukraine",
    capital: "Kiev",
    region: "Europe",
    population: 42692393,
  },
  {
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    region: "Asia",
    population: 9856000,
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    capital: "London",
    region: "Europe",
    population: 65110000,
  },
  {
    name: "United States of America",
    capital: "Washington, D.C.",
    region: "Americas",
    population: 323947000,
  },
  {
    name: "Uruguay",
    capital: "Montevideo",
    region: "Americas",
    population: 3480222,
  },
  {
    name: "Uzbekistan",
    capital: "Tashkent",
    region: "Asia",
    population: 31576400,
  },
  {
    name: "Vanuatu",
    capital: "Port Vila",
    region: "Oceania",
    population: 277500,
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    capital: "Caracas",
    region: "Americas",
    population: 31028700,
  },
  {
    name: "Viet Nam",
    capital: "Hanoi",
    region: "Asia",
    population: 92700000,
  },
  {
    name: "Wallis and Futuna",
    capital: "Mata-Utu",
    region: "Oceania",
    population: 11750,
  },
  {
    name: "Western Sahara",
    capital: "El Aaiún",
    region: "Africa",
    population: 510713,
  },
  {
    name: "Yemen",
    capital: "Sana'a",
    region: "Asia",
    population: 27478000,
  },
  {
    name: "Zambia",
    capital: "Lusaka",
    region: "Africa",
    population: 15933883,
  },
  {
    name: "Zimbabwe",
    capital: "Harare",
    region: "Africa",
    population: 14240168,
  },
];
